# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SHIFT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chip- Hotel Booking Chatbot
    pod 'ApiAI'

end
